// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingMessage struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (m *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(m, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Response struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type MyData struct {
	Msg                  []byte   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyData) Reset()         { *m = MyData{} }
func (m *MyData) String() string { return proto.CompactTextString(m) }
func (*MyData) ProtoMessage()    {}
func (*MyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *MyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyData.Unmarshal(m, b)
}
func (m *MyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyData.Marshal(b, m, deterministic)
}
func (m *MyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyData.Merge(m, src)
}
func (m *MyData) XXX_Size() int {
	return xxx_messageInfo_MyData.Size(m)
}
func (m *MyData) XXX_DiscardUnknown() {
	xxx_messageInfo_MyData.DiscardUnknown(m)
}

var xxx_messageInfo_MyData proto.InternalMessageInfo

func (m *MyData) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Test struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Test) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type Contact struct {
	ID                   []byte   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	QuorumID             int32    `protobuf:"varint,3,opt,name=QuorumID,proto3" json:"QuorumID,omitempty"`
	IsOracle             bool     `protobuf:"varint,4,opt,name=IsOracle,proto3" json:"IsOracle,omitempty"`
	IsLeader             bool     `protobuf:"varint,5,opt,name=IsLeader,proto3" json:"IsLeader,omitempty"`
	Oracle               []byte   `protobuf:"bytes,6,opt,name=Oracle,proto3" json:"Oracle,omitempty"`
	PubKey               string   `protobuf:"bytes,7,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	Category             string   `protobuf:"bytes,8,opt,name=Category,proto3" json:"Category,omitempty"`
	SelectedNumber       int32    `protobuf:"varint,9,opt,name=SelectedNumber,proto3" json:"SelectedNumber,omitempty"`
	SelectedTribe        int32    `protobuf:"varint,10,opt,name=SelectedTribe,proto3" json:"SelectedTribe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *Contact) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Contact) GetQuorumID() int32 {
	if m != nil {
		return m.QuorumID
	}
	return 0
}

func (m *Contact) GetIsOracle() bool {
	if m != nil {
		return m.IsOracle
	}
	return false
}

func (m *Contact) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

func (m *Contact) GetOracle() []byte {
	if m != nil {
		return m.Oracle
	}
	return nil
}

func (m *Contact) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *Contact) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Contact) GetSelectedNumber() int32 {
	if m != nil {
		return m.SelectedNumber
	}
	return 0
}

func (m *Contact) GetSelectedTribe() int32 {
	if m != nil {
		return m.SelectedTribe
	}
	return 0
}

type NodeID struct {
	NodeID               []byte   `protobuf:"bytes,1,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeID) Reset()         { *m = NodeID{} }
func (m *NodeID) String() string { return proto.CompactTextString(m) }
func (*NodeID) ProtoMessage()    {}
func (*NodeID) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *NodeID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeID.Unmarshal(m, b)
}
func (m *NodeID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeID.Marshal(b, m, deterministic)
}
func (m *NodeID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeID.Merge(m, src)
}
func (m *NodeID) XXX_Size() int {
	return xxx_messageInfo_NodeID.Size(m)
}
func (m *NodeID) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeID.DiscardUnknown(m)
}

var xxx_messageInfo_NodeID proto.InternalMessageInfo

func (m *NodeID) GetNodeID() []byte {
	if m != nil {
		return m.NodeID
	}
	return nil
}

type Share struct {
	Share                []byte   `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Share) Reset()         { *m = Share{} }
func (m *Share) String() string { return proto.CompactTextString(m) }
func (*Share) ProtoMessage()    {}
func (*Share) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *Share) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Share.Unmarshal(m, b)
}
func (m *Share) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Share.Marshal(b, m, deterministic)
}
func (m *Share) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Share.Merge(m, src)
}
func (m *Share) XXX_Size() int {
	return xxx_messageInfo_Share.Size(m)
}
func (m *Share) XXX_DiscardUnknown() {
	xxx_messageInfo_Share.DiscardUnknown(m)
}

var xxx_messageInfo_Share proto.InternalMessageInfo

func (m *Share) GetShare() []byte {
	if m != nil {
		return m.Share
	}
	return nil
}

type Shares struct {
	Share                []*Share `protobuf:"bytes,1,rep,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shares) Reset()         { *m = Shares{} }
func (m *Shares) String() string { return proto.CompactTextString(m) }
func (*Shares) ProtoMessage()    {}
func (*Shares) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *Shares) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shares.Unmarshal(m, b)
}
func (m *Shares) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shares.Marshal(b, m, deterministic)
}
func (m *Shares) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shares.Merge(m, src)
}
func (m *Shares) XXX_Size() int {
	return xxx_messageInfo_Shares.Size(m)
}
func (m *Shares) XXX_DiscardUnknown() {
	xxx_messageInfo_Shares.DiscardUnknown(m)
}

var xxx_messageInfo_Shares proto.InternalMessageInfo

func (m *Shares) GetShare() []*Share {
	if m != nil {
		return m.Share
	}
	return nil
}

type Contacts struct {
	Contact              []*Contact `protobuf:"bytes,1,rep,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Contacts) Reset()         { *m = Contacts{} }
func (m *Contacts) String() string { return proto.CompactTextString(m) }
func (*Contacts) ProtoMessage()    {}
func (*Contacts) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *Contacts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contacts.Unmarshal(m, b)
}
func (m *Contacts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contacts.Marshal(b, m, deterministic)
}
func (m *Contacts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contacts.Merge(m, src)
}
func (m *Contacts) XXX_Size() int {
	return xxx_messageInfo_Contacts.Size(m)
}
func (m *Contacts) XXX_DiscardUnknown() {
	xxx_messageInfo_Contacts.DiscardUnknown(m)
}

var xxx_messageInfo_Contacts proto.InternalMessageInfo

func (m *Contacts) GetContact() []*Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type Request struct {
	Action                           string                    `protobuf:"bytes,1,opt,name=Action,proto3" json:"Action,omitempty"`
	Data                             []byte                    `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	IsDKG                            bool                      `protobuf:"varint,3,opt,name=IsDKG,proto3" json:"IsDKG,omitempty"`
	Param                            string                    `protobuf:"bytes,4,opt,name=Param,proto3" json:"Param,omitempty"`
	Target                           *Contact                  `protobuf:"bytes,5,opt,name=Target,proto3" json:"Target,omitempty"`
	Value                            []byte                    `protobuf:"bytes,6,opt,name=Value,proto3" json:"Value,omitempty"`
	Sender                           *Contact                  `protobuf:"bytes,7,opt,name=Sender,proto3" json:"Sender,omitempty"`
	RPCHeader                        *RPCHeader                `protobuf:"bytes,8,opt,name=RPCHeader,proto3" json:"RPCHeader,omitempty"`
	NumberOfBatches                  int32                     `protobuf:"varint,9,opt,name=NumberOfBatches,proto3" json:"NumberOfBatches,omitempty"`
	NumberOfTransactionInSingleBatch int32                     `protobuf:"varint,10,opt,name=NumberOfTransactionInSingleBatch,proto3" json:"NumberOfTransactionInSingleBatch,omitempty"`
	TransactionType                  string                    `protobuf:"bytes,11,opt,name=TransactionType,proto3" json:"TransactionType,omitempty"`
	RSIPGroup                        int32                     `protobuf:"varint,12,opt,name=RSIPGroup,proto3" json:"RSIPGroup,omitempty"`
	Hash                             []byte                    `protobuf:"bytes,13,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Signature                        []byte                    `protobuf:"bytes,14,opt,name=Signature,proto3" json:"Signature,omitempty"`
	System                           []byte                    `protobuf:"bytes,15,opt,name=system,proto3" json:"system,omitempty"`
	Index                            int32                     `protobuf:"varint,16,opt,name=index,proto3" json:"index,omitempty"`
	BatchID                          string                    `protobuf:"bytes,17,opt,name=BatchID,proto3" json:"BatchID,omitempty"`
	LeaderGroup                      int32                     `protobuf:"varint,18,opt,name=LeaderGroup,proto3" json:"LeaderGroup,omitempty"`
	BatchProposerLeader              string                    `protobuf:"bytes,19,opt,name=BatchProposerLeader,proto3" json:"BatchProposerLeader,omitempty"`
	DHTContact                       *Contact                  `protobuf:"bytes,20,opt,name=DHTContact,proto3" json:"DHTContact,omitempty"`
	ByteSize                         int64                     `protobuf:"varint,21,opt,name=ByteSize,proto3" json:"ByteSize,omitempty"`
	TribeNumber                      int32                     `protobuf:"varint,22,opt,name=TribeNumber,proto3" json:"TribeNumber,omitempty"`
	AggregatedSignatures             *Shares                   `protobuf:"bytes,23,opt,name=AggregatedSignatures,proto3" json:"AggregatedSignatures,omitempty"`
	SingleTransaction                *TransactionWithSignature `protobuf:"bytes,24,opt,name=SingleTransaction,proto3" json:"SingleTransaction,omitempty"`
	TransactionToken                 string                    `protobuf:"bytes,25,opt,name=TransactionToken,proto3" json:"TransactionToken,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}                  `json:"-"`
	XXX_unrecognized                 []byte                    `json:"-"`
	XXX_sizecache                    int32                     `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Request) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Request) GetIsDKG() bool {
	if m != nil {
		return m.IsDKG
	}
	return false
}

func (m *Request) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *Request) GetTarget() *Contact {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Request) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Request) GetSender() *Contact {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Request) GetRPCHeader() *RPCHeader {
	if m != nil {
		return m.RPCHeader
	}
	return nil
}

func (m *Request) GetNumberOfBatches() int32 {
	if m != nil {
		return m.NumberOfBatches
	}
	return 0
}

func (m *Request) GetNumberOfTransactionInSingleBatch() int32 {
	if m != nil {
		return m.NumberOfTransactionInSingleBatch
	}
	return 0
}

func (m *Request) GetTransactionType() string {
	if m != nil {
		return m.TransactionType
	}
	return ""
}

func (m *Request) GetRSIPGroup() int32 {
	if m != nil {
		return m.RSIPGroup
	}
	return 0
}

func (m *Request) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Request) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Request) GetSystem() []byte {
	if m != nil {
		return m.System
	}
	return nil
}

func (m *Request) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Request) GetBatchID() string {
	if m != nil {
		return m.BatchID
	}
	return ""
}

func (m *Request) GetLeaderGroup() int32 {
	if m != nil {
		return m.LeaderGroup
	}
	return 0
}

func (m *Request) GetBatchProposerLeader() string {
	if m != nil {
		return m.BatchProposerLeader
	}
	return ""
}

func (m *Request) GetDHTContact() *Contact {
	if m != nil {
		return m.DHTContact
	}
	return nil
}

func (m *Request) GetByteSize() int64 {
	if m != nil {
		return m.ByteSize
	}
	return 0
}

func (m *Request) GetTribeNumber() int32 {
	if m != nil {
		return m.TribeNumber
	}
	return 0
}

func (m *Request) GetAggregatedSignatures() *Shares {
	if m != nil {
		return m.AggregatedSignatures
	}
	return nil
}

func (m *Request) GetSingleTransaction() *TransactionWithSignature {
	if m != nil {
		return m.SingleTransaction
	}
	return nil
}

func (m *Request) GetTransactionToken() string {
	if m != nil {
		return m.TransactionToken
	}
	return ""
}

type VerifiedResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifiedResponse) Reset()         { *m = VerifiedResponse{} }
func (m *VerifiedResponse) String() string { return proto.CompactTextString(m) }
func (*VerifiedResponse) ProtoMessage()    {}
func (*VerifiedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *VerifiedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifiedResponse.Unmarshal(m, b)
}
func (m *VerifiedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifiedResponse.Marshal(b, m, deterministic)
}
func (m *VerifiedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifiedResponse.Merge(m, src)
}
func (m *VerifiedResponse) XXX_Size() int {
	return xxx_messageInfo_VerifiedResponse.Size(m)
}
func (m *VerifiedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifiedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifiedResponse proto.InternalMessageInfo

func (m *VerifiedResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RPCHeader struct {
	Sender               *Contact `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCHeader) Reset()         { *m = RPCHeader{} }
func (m *RPCHeader) String() string { return proto.CompactTextString(m) }
func (*RPCHeader) ProtoMessage()    {}
func (*RPCHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *RPCHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCHeader.Unmarshal(m, b)
}
func (m *RPCHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCHeader.Marshal(b, m, deterministic)
}
func (m *RPCHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCHeader.Merge(m, src)
}
func (m *RPCHeader) XXX_Size() int {
	return xxx_messageInfo_RPCHeader.Size(m)
}
func (m *RPCHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RPCHeader proto.InternalMessageInfo

func (m *RPCHeader) GetSender() *Contact {
	if m != nil {
		return m.Sender
	}
	return nil
}

type VoteResponses struct {
	VoteResponse         []*VoteResponse `protobuf:"bytes,1,rep,name=voteResponse,proto3" json:"voteResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *VoteResponses) Reset()         { *m = VoteResponses{} }
func (m *VoteResponses) String() string { return proto.CompactTextString(m) }
func (*VoteResponses) ProtoMessage()    {}
func (*VoteResponses) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *VoteResponses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteResponses.Unmarshal(m, b)
}
func (m *VoteResponses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteResponses.Marshal(b, m, deterministic)
}
func (m *VoteResponses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteResponses.Merge(m, src)
}
func (m *VoteResponses) XXX_Size() int {
	return xxx_messageInfo_VoteResponses.Size(m)
}
func (m *VoteResponses) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteResponses.DiscardUnknown(m)
}

var xxx_messageInfo_VoteResponses proto.InternalMessageInfo

func (m *VoteResponses) GetVoteResponse() []*VoteResponse {
	if m != nil {
		return m.VoteResponse
	}
	return nil
}

type FindNodeResponse struct {
	RPCHeader            *RPCHeader    `protobuf:"bytes,1,opt,name=RPCHeader,proto3" json:"RPCHeader,omitempty"`
	Contacts             *Contacts     `protobuf:"bytes,2,opt,name=Contacts,proto3" json:"Contacts,omitempty"`
	Value                *Contacts     `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	Vote                 string        `protobuf:"bytes,4,opt,name=Vote,proto3" json:"Vote,omitempty"`
	Verified             string        `protobuf:"bytes,5,opt,name=Verified,proto3" json:"Verified,omitempty"`
	Data                 []byte        `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
	Data2                *VoteResponse `protobuf:"bytes,7,opt,name=Data2,proto3" json:"Data2,omitempty"`
	IsTransection        bool          `protobuf:"varint,8,opt,name=IsTransection,proto3" json:"IsTransection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FindNodeResponse) Reset()         { *m = FindNodeResponse{} }
func (m *FindNodeResponse) String() string { return proto.CompactTextString(m) }
func (*FindNodeResponse) ProtoMessage()    {}
func (*FindNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *FindNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindNodeResponse.Unmarshal(m, b)
}
func (m *FindNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindNodeResponse.Marshal(b, m, deterministic)
}
func (m *FindNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindNodeResponse.Merge(m, src)
}
func (m *FindNodeResponse) XXX_Size() int {
	return xxx_messageInfo_FindNodeResponse.Size(m)
}
func (m *FindNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindNodeResponse proto.InternalMessageInfo

func (m *FindNodeResponse) GetRPCHeader() *RPCHeader {
	if m != nil {
		return m.RPCHeader
	}
	return nil
}

func (m *FindNodeResponse) GetContacts() *Contacts {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *FindNodeResponse) GetValue() *Contacts {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *FindNodeResponse) GetVote() string {
	if m != nil {
		return m.Vote
	}
	return ""
}

func (m *FindNodeResponse) GetVerified() string {
	if m != nil {
		return m.Verified
	}
	return ""
}

func (m *FindNodeResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *FindNodeResponse) GetData2() *VoteResponse {
	if m != nil {
		return m.Data2
	}
	return nil
}

func (m *FindNodeResponse) GetIsTransection() bool {
	if m != nil {
		return m.IsTransection
	}
	return false
}

type VoteResponse struct {
	ID                   []byte   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TransactionID        string   `protobuf:"bytes,2,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Vote                 string   `protobuf:"bytes,4,opt,name=Vote,proto3" json:"Vote,omitempty"`
	Reason               string   `protobuf:"bytes,5,opt,name=Reason,proto3" json:"Reason,omitempty"`
	Threshold            string   `protobuf:"bytes,6,opt,name=Threshold,proto3" json:"Threshold,omitempty"`
	ThresholdOfRSIP      string   `protobuf:"bytes,7,opt,name=ThresholdOfRSIP,proto3" json:"ThresholdOfRSIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteResponse) Reset()         { *m = VoteResponse{} }
func (m *VoteResponse) String() string { return proto.CompactTextString(m) }
func (*VoteResponse) ProtoMessage()    {}
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *VoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteResponse.Unmarshal(m, b)
}
func (m *VoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteResponse.Marshal(b, m, deterministic)
}
func (m *VoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteResponse.Merge(m, src)
}
func (m *VoteResponse) XXX_Size() int {
	return xxx_messageInfo_VoteResponse.Size(m)
}
func (m *VoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VoteResponse proto.InternalMessageInfo

func (m *VoteResponse) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *VoteResponse) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *VoteResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *VoteResponse) GetVote() string {
	if m != nil {
		return m.Vote
	}
	return ""
}

func (m *VoteResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *VoteResponse) GetThreshold() string {
	if m != nil {
		return m.Threshold
	}
	return ""
}

func (m *VoteResponse) GetThresholdOfRSIP() string {
	if m != nil {
		return m.ThresholdOfRSIP
	}
	return ""
}

type BootstarpSyncResponse struct {
	Contacts             *Contacts `protobuf:"bytes,1,opt,name=Contacts,proto3" json:"Contacts,omitempty"`
	Data                 []byte    `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BootstarpSyncResponse) Reset()         { *m = BootstarpSyncResponse{} }
func (m *BootstarpSyncResponse) String() string { return proto.CompactTextString(m) }
func (*BootstarpSyncResponse) ProtoMessage()    {}
func (*BootstarpSyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *BootstarpSyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootstarpSyncResponse.Unmarshal(m, b)
}
func (m *BootstarpSyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootstarpSyncResponse.Marshal(b, m, deterministic)
}
func (m *BootstarpSyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootstarpSyncResponse.Merge(m, src)
}
func (m *BootstarpSyncResponse) XXX_Size() int {
	return xxx_messageInfo_BootstarpSyncResponse.Size(m)
}
func (m *BootstarpSyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BootstarpSyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BootstarpSyncResponse proto.InternalMessageInfo

func (m *BootstarpSyncResponse) GetContacts() *Contacts {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *BootstarpSyncResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Byte struct {
	Msg                  []byte   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Byte) Reset()         { *m = Byte{} }
func (m *Byte) String() string { return proto.CompactTextString(m) }
func (*Byte) ProtoMessage()    {}
func (*Byte) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *Byte) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Byte.Unmarshal(m, b)
}
func (m *Byte) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Byte.Marshal(b, m, deterministic)
}
func (m *Byte) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Byte.Merge(m, src)
}
func (m *Byte) XXX_Size() int {
	return xxx_messageInfo_Byte.Size(m)
}
func (m *Byte) XXX_DiscardUnknown() {
	xxx_messageInfo_Byte.DiscardUnknown(m)
}

var xxx_messageInfo_Byte proto.InternalMessageInfo

func (m *Byte) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type RSIPResponse struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	BatchID              string   `protobuf:"bytes,3,opt,name=BatchID,proto3" json:"BatchID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RSIPResponse) Reset()         { *m = RSIPResponse{} }
func (m *RSIPResponse) String() string { return proto.CompactTextString(m) }
func (*RSIPResponse) ProtoMessage()    {}
func (*RSIPResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *RSIPResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RSIPResponse.Unmarshal(m, b)
}
func (m *RSIPResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RSIPResponse.Marshal(b, m, deterministic)
}
func (m *RSIPResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RSIPResponse.Merge(m, src)
}
func (m *RSIPResponse) XXX_Size() int {
	return xxx_messageInfo_RSIPResponse.Size(m)
}
func (m *RSIPResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RSIPResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RSIPResponse proto.InternalMessageInfo

func (m *RSIPResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *RSIPResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *RSIPResponse) GetBatchID() string {
	if m != nil {
		return m.BatchID
	}
	return ""
}

type TransactionWithSignature struct {
	ID                   string         `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	From                 string         `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	To                   string         `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	Amount               int32          `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Signature            []byte         `protobuf:"bytes,5,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Status               string         `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
	Reason               []string       `protobuf:"bytes,7,rep,name=Reason,proto3" json:"Reason,omitempty"`
	Leaders              *VoteResponses `protobuf:"bytes,8,opt,name=Leaders,proto3" json:"Leaders,omitempty"`
	Oracles              *VoteResponses `protobuf:"bytes,9,opt,name=Oracles,proto3" json:"Oracles,omitempty"`
	RSIP                 *VoteResponses `protobuf:"bytes,10,opt,name=RSIP,proto3" json:"RSIP,omitempty"`
	Message              string         `protobuf:"bytes,11,opt,name=Message,proto3" json:"Message,omitempty"`
	BatchID              string         `protobuf:"bytes,12,opt,name=BatchID,proto3" json:"BatchID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransactionWithSignature) Reset()         { *m = TransactionWithSignature{} }
func (m *TransactionWithSignature) String() string { return proto.CompactTextString(m) }
func (*TransactionWithSignature) ProtoMessage()    {}
func (*TransactionWithSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *TransactionWithSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionWithSignature.Unmarshal(m, b)
}
func (m *TransactionWithSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionWithSignature.Marshal(b, m, deterministic)
}
func (m *TransactionWithSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionWithSignature.Merge(m, src)
}
func (m *TransactionWithSignature) XXX_Size() int {
	return xxx_messageInfo_TransactionWithSignature.Size(m)
}
func (m *TransactionWithSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionWithSignature.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionWithSignature proto.InternalMessageInfo

func (m *TransactionWithSignature) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *TransactionWithSignature) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TransactionWithSignature) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransactionWithSignature) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransactionWithSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *TransactionWithSignature) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TransactionWithSignature) GetReason() []string {
	if m != nil {
		return m.Reason
	}
	return nil
}

func (m *TransactionWithSignature) GetLeaders() *VoteResponses {
	if m != nil {
		return m.Leaders
	}
	return nil
}

func (m *TransactionWithSignature) GetOracles() *VoteResponses {
	if m != nil {
		return m.Oracles
	}
	return nil
}

func (m *TransactionWithSignature) GetRSIP() *VoteResponses {
	if m != nil {
		return m.RSIP
	}
	return nil
}

func (m *TransactionWithSignature) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TransactionWithSignature) GetBatchID() string {
	if m != nil {
		return m.BatchID
	}
	return ""
}

type NewTransection struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount               int32    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Signature            string   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTransection) Reset()         { *m = NewTransection{} }
func (m *NewTransection) String() string { return proto.CompactTextString(m) }
func (*NewTransection) ProtoMessage()    {}
func (*NewTransection) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *NewTransection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTransection.Unmarshal(m, b)
}
func (m *NewTransection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTransection.Marshal(b, m, deterministic)
}
func (m *NewTransection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTransection.Merge(m, src)
}
func (m *NewTransection) XXX_Size() int {
	return xxx_messageInfo_NewTransection.Size(m)
}
func (m *NewTransection) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTransection.DiscardUnknown(m)
}

var xxx_messageInfo_NewTransection proto.InternalMessageInfo

func (m *NewTransection) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *NewTransection) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *NewTransection) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *NewTransection) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type NewTransections struct {
	NewTransection       []*NewTransection `protobuf:"bytes,1,rep,name=NewTransection,proto3" json:"NewTransection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NewTransections) Reset()         { *m = NewTransections{} }
func (m *NewTransections) String() string { return proto.CompactTextString(m) }
func (*NewTransections) ProtoMessage()    {}
func (*NewTransections) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}

func (m *NewTransections) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTransections.Unmarshal(m, b)
}
func (m *NewTransections) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTransections.Marshal(b, m, deterministic)
}
func (m *NewTransections) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTransections.Merge(m, src)
}
func (m *NewTransections) XXX_Size() int {
	return xxx_messageInfo_NewTransections.Size(m)
}
func (m *NewTransections) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTransections.DiscardUnknown(m)
}

var xxx_messageInfo_NewTransections proto.InternalMessageInfo

func (m *NewTransections) GetNewTransection() []*NewTransection {
	if m != nil {
		return m.NewTransection
	}
	return nil
}

type TransactionWithSignatures struct {
	TransactionWithSignature []*TransactionWithSignature `protobuf:"bytes,1,rep,name=transactionWithSignature,proto3" json:"transactionWithSignature,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                    `json:"-"`
	XXX_unrecognized         []byte                      `json:"-"`
	XXX_sizecache            int32                       `json:"-"`
}

func (m *TransactionWithSignatures) Reset()         { *m = TransactionWithSignatures{} }
func (m *TransactionWithSignatures) String() string { return proto.CompactTextString(m) }
func (*TransactionWithSignatures) ProtoMessage()    {}
func (*TransactionWithSignatures) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}

func (m *TransactionWithSignatures) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionWithSignatures.Unmarshal(m, b)
}
func (m *TransactionWithSignatures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionWithSignatures.Marshal(b, m, deterministic)
}
func (m *TransactionWithSignatures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionWithSignatures.Merge(m, src)
}
func (m *TransactionWithSignatures) XXX_Size() int {
	return xxx_messageInfo_TransactionWithSignatures.Size(m)
}
func (m *TransactionWithSignatures) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionWithSignatures.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionWithSignatures proto.InternalMessageInfo

func (m *TransactionWithSignatures) GetTransactionWithSignature() []*TransactionWithSignature {
	if m != nil {
		return m.TransactionWithSignature
	}
	return nil
}

type Client struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey            string   `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	PrivateKey           string   `protobuf:"bytes,4,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	Amount               int32    `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{23}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Client) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Client) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Client) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *Client) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type Clients struct {
	Client               []*Client `protobuf:"bytes,1,rep,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Clients) Reset()         { *m = Clients{} }
func (m *Clients) String() string { return proto.CompactTextString(m) }
func (*Clients) ProtoMessage()    {}
func (*Clients) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{24}
}

func (m *Clients) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clients.Unmarshal(m, b)
}
func (m *Clients) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clients.Marshal(b, m, deterministic)
}
func (m *Clients) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clients.Merge(m, src)
}
func (m *Clients) XXX_Size() int {
	return xxx_messageInfo_Clients.Size(m)
}
func (m *Clients) XXX_DiscardUnknown() {
	xxx_messageInfo_Clients.DiscardUnknown(m)
}

var xxx_messageInfo_Clients proto.InternalMessageInfo

func (m *Clients) GetClient() []*Client {
	if m != nil {
		return m.Client
	}
	return nil
}

type BatchTransaction struct {
	ID                   string                      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Data                 []*TransactionWithSignature `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Signature            []byte                      `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *BatchTransaction) Reset()         { *m = BatchTransaction{} }
func (m *BatchTransaction) String() string { return proto.CompactTextString(m) }
func (*BatchTransaction) ProtoMessage()    {}
func (*BatchTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{25}
}

func (m *BatchTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchTransaction.Unmarshal(m, b)
}
func (m *BatchTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchTransaction.Marshal(b, m, deterministic)
}
func (m *BatchTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchTransaction.Merge(m, src)
}
func (m *BatchTransaction) XXX_Size() int {
	return xxx_messageInfo_BatchTransaction.Size(m)
}
func (m *BatchTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_BatchTransaction proto.InternalMessageInfo

func (m *BatchTransaction) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *BatchTransaction) GetData() []*TransactionWithSignature {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BatchTransaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type BatchTransactions struct {
	BatchTransaction     []*BatchTransaction `protobuf:"bytes,1,rep,name=BatchTransaction,proto3" json:"BatchTransaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BatchTransactions) Reset()         { *m = BatchTransactions{} }
func (m *BatchTransactions) String() string { return proto.CompactTextString(m) }
func (*BatchTransactions) ProtoMessage()    {}
func (*BatchTransactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{26}
}

func (m *BatchTransactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchTransactions.Unmarshal(m, b)
}
func (m *BatchTransactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchTransactions.Marshal(b, m, deterministic)
}
func (m *BatchTransactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchTransactions.Merge(m, src)
}
func (m *BatchTransactions) XXX_Size() int {
	return xxx_messageInfo_BatchTransactions.Size(m)
}
func (m *BatchTransactions) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchTransactions.DiscardUnknown(m)
}

var xxx_messageInfo_BatchTransactions proto.InternalMessageInfo

func (m *BatchTransactions) GetBatchTransaction() []*BatchTransaction {
	if m != nil {
		return m.BatchTransaction
	}
	return nil
}

type Key struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{27}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RSIPDecimal struct {
	Group                int32    `protobuf:"varint,1,opt,name=Group,proto3" json:"Group,omitempty"`
	Decimal              int32    `protobuf:"varint,2,opt,name=Decimal,proto3" json:"Decimal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RSIPDecimal) Reset()         { *m = RSIPDecimal{} }
func (m *RSIPDecimal) String() string { return proto.CompactTextString(m) }
func (*RSIPDecimal) ProtoMessage()    {}
func (*RSIPDecimal) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{28}
}

func (m *RSIPDecimal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RSIPDecimal.Unmarshal(m, b)
}
func (m *RSIPDecimal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RSIPDecimal.Marshal(b, m, deterministic)
}
func (m *RSIPDecimal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RSIPDecimal.Merge(m, src)
}
func (m *RSIPDecimal) XXX_Size() int {
	return xxx_messageInfo_RSIPDecimal.Size(m)
}
func (m *RSIPDecimal) XXX_DiscardUnknown() {
	xxx_messageInfo_RSIPDecimal.DiscardUnknown(m)
}

var xxx_messageInfo_RSIPDecimal proto.InternalMessageInfo

func (m *RSIPDecimal) GetGroup() int32 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *RSIPDecimal) GetDecimal() int32 {
	if m != nil {
		return m.Decimal
	}
	return 0
}

type RSIPDecimals struct {
	RSIPDecimal          []*RSIPDecimal `protobuf:"bytes,1,rep,name=RSIPDecimal,proto3" json:"RSIPDecimal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RSIPDecimals) Reset()         { *m = RSIPDecimals{} }
func (m *RSIPDecimals) String() string { return proto.CompactTextString(m) }
func (*RSIPDecimals) ProtoMessage()    {}
func (*RSIPDecimals) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{29}
}

func (m *RSIPDecimals) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RSIPDecimals.Unmarshal(m, b)
}
func (m *RSIPDecimals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RSIPDecimals.Marshal(b, m, deterministic)
}
func (m *RSIPDecimals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RSIPDecimals.Merge(m, src)
}
func (m *RSIPDecimals) XXX_Size() int {
	return xxx_messageInfo_RSIPDecimals.Size(m)
}
func (m *RSIPDecimals) XXX_DiscardUnknown() {
	xxx_messageInfo_RSIPDecimals.DiscardUnknown(m)
}

var xxx_messageInfo_RSIPDecimals proto.InternalMessageInfo

func (m *RSIPDecimals) GetRSIPDecimal() []*RSIPDecimal {
	if m != nil {
		return m.RSIPDecimal
	}
	return nil
}

type AlphaOracleToOtherOracles struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlphaOracleToOtherOracles) Reset()         { *m = AlphaOracleToOtherOracles{} }
func (m *AlphaOracleToOtherOracles) String() string { return proto.CompactTextString(m) }
func (*AlphaOracleToOtherOracles) ProtoMessage()    {}
func (*AlphaOracleToOtherOracles) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{30}
}

func (m *AlphaOracleToOtherOracles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlphaOracleToOtherOracles.Unmarshal(m, b)
}
func (m *AlphaOracleToOtherOracles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlphaOracleToOtherOracles.Marshal(b, m, deterministic)
}
func (m *AlphaOracleToOtherOracles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlphaOracleToOtherOracles.Merge(m, src)
}
func (m *AlphaOracleToOtherOracles) XXX_Size() int {
	return xxx_messageInfo_AlphaOracleToOtherOracles.Size(m)
}
func (m *AlphaOracleToOtherOracles) XXX_DiscardUnknown() {
	xxx_messageInfo_AlphaOracleToOtherOracles.DiscardUnknown(m)
}

var xxx_messageInfo_AlphaOracleToOtherOracles proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PingMessage)(nil), "api.PingMessage")
	proto.RegisterType((*Empty)(nil), "api.Empty")
	proto.RegisterType((*Response)(nil), "api.Response")
	proto.RegisterType((*MyData)(nil), "api.MyData")
	proto.RegisterType((*Test)(nil), "api.Test")
	proto.RegisterType((*Contact)(nil), "api.Contact")
	proto.RegisterType((*NodeID)(nil), "api.NodeID")
	proto.RegisterType((*Share)(nil), "api.Share")
	proto.RegisterType((*Shares)(nil), "api.Shares")
	proto.RegisterType((*Contacts)(nil), "api.Contacts")
	proto.RegisterType((*Request)(nil), "api.Request")
	proto.RegisterType((*VerifiedResponse)(nil), "api.VerifiedResponse")
	proto.RegisterType((*RPCHeader)(nil), "api.RPCHeader")
	proto.RegisterType((*VoteResponses)(nil), "api.VoteResponses")
	proto.RegisterType((*FindNodeResponse)(nil), "api.FindNodeResponse")
	proto.RegisterType((*VoteResponse)(nil), "api.VoteResponse")
	proto.RegisterType((*BootstarpSyncResponse)(nil), "api.BootstarpSyncResponse")
	proto.RegisterType((*Byte)(nil), "api.byte")
	proto.RegisterType((*RSIPResponse)(nil), "api.RSIPResponse")
	proto.RegisterType((*TransactionWithSignature)(nil), "api.TransactionWithSignature")
	proto.RegisterType((*NewTransection)(nil), "api.NewTransection")
	proto.RegisterType((*NewTransections)(nil), "api.NewTransections")
	proto.RegisterType((*TransactionWithSignatures)(nil), "api.TransactionWithSignatures")
	proto.RegisterType((*Client)(nil), "api.Client")
	proto.RegisterType((*Clients)(nil), "api.Clients")
	proto.RegisterType((*BatchTransaction)(nil), "api.BatchTransaction")
	proto.RegisterType((*BatchTransactions)(nil), "api.BatchTransactions")
	proto.RegisterType((*Key)(nil), "api.key")
	proto.RegisterType((*RSIPDecimal)(nil), "api.RSIPDecimal")
	proto.RegisterType((*RSIPDecimals)(nil), "api.RSIPDecimals")
	proto.RegisterType((*AlphaOracleToOtherOracles)(nil), "api.AlphaOracleToOtherOracles")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 1461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xeb, 0x6e, 0x1b, 0xb7,
	0x12, 0x8e, 0xee, 0xd2, 0x48, 0x76, 0x6c, 0x26, 0x71, 0x18, 0x9f, 0x93, 0x03, 0x81, 0x27, 0x48,
	0x9d, 0xc0, 0x08, 0x12, 0x15, 0x05, 0x0a, 0x14, 0x45, 0x61, 0x5b, 0x4d, 0xac, 0xa6, 0xb1, 0x5d,
	0x4a, 0x70, 0xd1, 0xfe, 0xa3, 0x24, 0x5a, 0xda, 0x46, 0xda, 0x55, 0x97, 0x54, 0x5a, 0xf5, 0x19,
	0xfa, 0x12, 0x45, 0x80, 0x3e, 0x50, 0x9f, 0xa3, 0x0f, 0x51, 0x70, 0xc8, 0x5d, 0x71, 0x75, 0x69,
	0xda, 0x5f, 0xe2, 0xdc, 0xc8, 0xd9, 0xf9, 0x38, 0xdf, 0x50, 0x50, 0x13, 0xb3, 0xe0, 0xd9, 0x2c,
	0x8e, 0x74, 0x44, 0x0a, 0x62, 0x16, 0xb0, 0x27, 0x50, 0xbf, 0x0a, 0xc2, 0xd1, 0x1b, 0xa9, 0x94,
	0x18, 0x49, 0x72, 0x08, 0xd5, 0x51, 0x2c, 0xa5, 0x0e, 0xc2, 0x11, 0xcd, 0x35, 0x73, 0x47, 0x35,
	0x9e, 0xca, 0xac, 0x02, 0xa5, 0x2f, 0xa7, 0x33, 0xbd, 0x60, 0x4d, 0xa8, 0x72, 0xa9, 0x66, 0x51,
	0xa8, 0x24, 0xb9, 0x0b, 0xa5, 0x6b, 0x31, 0x99, 0x4b, 0xf4, 0x6e, 0x70, 0x2b, 0xb0, 0x43, 0x28,
	0xbf, 0x59, 0xb4, 0x85, 0x16, 0x64, 0x0f, 0x0a, 0x6f, 0xd4, 0xc8, 0x59, 0xcd, 0x92, 0x3d, 0x87,
	0x62, 0x4f, 0x2a, 0x6d, 0x22, 0x27, 0xa2, 0x2f, 0x27, 0xee, 0x1c, 0x2b, 0x10, 0x02, 0x45, 0xbd,
	0x98, 0x49, 0x9a, 0x6f, 0xe6, 0x8e, 0x4a, 0x1c, 0xd7, 0xec, 0xb7, 0x3c, 0x54, 0xce, 0xa2, 0x50,
	0x8b, 0x81, 0x26, 0xbb, 0x90, 0xef, 0xb4, 0xdd, 0x76, 0xf9, 0x4e, 0x9b, 0x50, 0xa8, 0x9c, 0x0c,
	0x87, 0xb1, 0x54, 0x0a, 0x43, 0x6a, 0x3c, 0x11, 0xcd, 0xa7, 0x7c, 0x33, 0x8f, 0xe2, 0xf9, 0xb4,
	0xd3, 0xa6, 0x05, 0xdc, 0x2d, 0x95, 0x8d, 0xad, 0xa3, 0x2e, 0x63, 0x31, 0x98, 0x48, 0x5a, 0x6c,
	0xe6, 0x8e, 0xaa, 0x3c, 0x95, 0xad, 0xed, 0x6b, 0x29, 0x86, 0x32, 0xa6, 0xa5, 0xc4, 0x66, 0x65,
	0x72, 0x00, 0x65, 0x17, 0x55, 0xc6, 0x0c, 0x9c, 0x64, 0xf4, 0x57, 0xf3, 0xfe, 0x6b, 0xb9, 0xa0,
	0x15, 0x4c, 0xc2, 0x49, 0x66, 0xaf, 0x33, 0xa1, 0xe5, 0x28, 0x8a, 0x17, 0xb4, 0x6a, 0xcb, 0x99,
	0xc8, 0xe4, 0x31, 0xec, 0x76, 0xe5, 0x44, 0x0e, 0xb4, 0x1c, 0x5e, 0xcc, 0xa7, 0x7d, 0x19, 0xd3,
	0x1a, 0x66, 0xb9, 0xa2, 0x25, 0x8f, 0x60, 0x27, 0xd1, 0xf4, 0xe2, 0xa0, 0x2f, 0x29, 0xa0, 0x5b,
	0x56, 0xc9, 0x9a, 0x50, 0xbe, 0x88, 0x86, 0xb2, 0xd3, 0x36, 0xb9, 0xd8, 0x95, 0xab, 0x92, 0x93,
	0xd8, 0x43, 0x28, 0x75, 0xc7, 0x22, 0x46, 0xc8, 0x94, 0x59, 0x24, 0x90, 0xa1, 0xc0, 0x9e, 0x42,
	0x19, 0xcd, 0x8a, 0x34, 0x97, 0xf6, 0xc2, 0x51, 0xbd, 0x05, 0xcf, 0xcc, 0x95, 0x41, 0x5b, 0xe2,
	0xdb, 0x82, 0xaa, 0xc3, 0x43, 0x91, 0xc7, 0x50, 0x19, 0xd8, 0xb5, 0xf3, 0x6f, 0xa0, 0xbf, 0xb3,
	0xf3, 0xc4, 0xc8, 0xde, 0x57, 0xa0, 0xc2, 0xe5, 0x8f, 0x73, 0x03, 0xfd, 0x01, 0x94, 0x4f, 0x06,
	0x3a, 0x88, 0x42, 0x87, 0xbd, 0x93, 0x0c, 0xf8, 0xe6, 0xd2, 0x20, 0x92, 0x0d, 0x8e, 0x6b, 0x93,
	0x6d, 0x47, 0xb5, 0x5f, 0xbf, 0x42, 0x0c, 0xab, 0xdc, 0x0a, 0x46, 0x7b, 0x25, 0x62, 0x31, 0x45,
	0xf4, 0x6a, 0xdc, 0x0a, 0xe4, 0x11, 0x94, 0x7b, 0x22, 0x1e, 0x49, 0x8d, 0xc0, 0xad, 0xa6, 0xe2,
	0x6c, 0xcb, 0x2b, 0x5b, 0xf6, 0xae, 0xac, 0x89, 0xed, 0xca, 0xd0, 0x80, 0x5e, 0xd9, 0x14, 0x6b,
	0x6d, 0xe4, 0x18, 0x6a, 0xfc, 0xea, 0xec, 0xdc, 0xde, 0x8e, 0x2a, 0x3a, 0xee, 0xa2, 0x63, 0xaa,
	0xe5, 0x4b, 0x07, 0x72, 0x04, 0xb7, 0x2d, 0x88, 0x97, 0x37, 0xa7, 0x42, 0x0f, 0xc6, 0x52, 0x39,
	0x8c, 0x57, 0xd5, 0xe4, 0x2b, 0x68, 0x26, 0xaa, 0x5e, 0x2c, 0x42, 0x25, 0xb0, 0x20, 0x9d, 0xb0,
	0x1b, 0x84, 0xa3, 0x89, 0x44, 0x2f, 0x87, 0xfb, 0x07, 0xfd, 0xcc, 0xa9, 0x9e, 0xad, 0x67, 0xba,
	0xa9, 0x8e, 0x55, 0x5a, 0x55, 0x93, 0xff, 0x42, 0x8d, 0x77, 0x3b, 0x57, 0xaf, 0xe2, 0x68, 0x3e,
	0xa3, 0x0d, 0xdc, 0x7e, 0xa9, 0x30, 0x68, 0x9c, 0x0b, 0x35, 0xa6, 0x3b, 0x16, 0x0d, 0xb3, 0x36,
	0x11, 0xdd, 0x60, 0x14, 0x0a, 0x3d, 0x8f, 0x25, 0xdd, 0x45, 0xc3, 0x52, 0x61, 0x70, 0x55, 0x0b,
	0xa5, 0xe5, 0x94, 0xde, 0xb6, 0x57, 0xcf, 0x4a, 0xa6, 0xe2, 0x41, 0x38, 0x94, 0x3f, 0xd3, 0x3d,
	0x3c, 0xc3, 0x0a, 0xa6, 0x75, 0x31, 0xe1, 0x4e, 0x9b, 0xee, 0xdb, 0xd6, 0x75, 0x22, 0x69, 0x42,
	0xdd, 0x36, 0x9c, 0xcd, 0x8c, 0x60, 0x94, 0xaf, 0x22, 0xcf, 0xe1, 0x0e, 0x3a, 0x5f, 0xc5, 0xd1,
	0x2c, 0x52, 0x32, 0x76, 0xfd, 0x7a, 0x07, 0xf7, 0xd9, 0x64, 0x22, 0xc7, 0x00, 0xed, 0xf3, 0x9e,
	0xc3, 0x93, 0xde, 0xdd, 0x80, 0xb1, 0x67, 0x37, 0x8d, 0x7b, 0xba, 0xd0, 0xb2, 0x1b, 0xfc, 0x22,
	0xe9, 0xbd, 0x66, 0xee, 0xa8, 0xc0, 0x53, 0xd9, 0x64, 0x87, 0x3d, 0xe7, 0xba, 0xf6, 0xc0, 0x66,
	0xe7, 0xa9, 0xc8, 0x17, 0x70, 0xf7, 0x64, 0x34, 0x8a, 0xe5, 0x48, 0x68, 0x39, 0x4c, 0xcb, 0xa3,
	0xe8, 0x7d, 0x3c, 0xb5, 0xbe, 0x6c, 0x28, 0xc5, 0x37, 0x3a, 0x92, 0xd7, 0xb0, 0x6f, 0x11, 0xf5,
	0x10, 0xa3, 0x14, 0xa3, 0x1f, 0x62, 0xb4, 0xa7, 0xff, 0x36, 0xd0, 0xe3, 0x34, 0x94, 0xaf, 0xc7,
	0x91, 0xa7, 0xb0, 0xe7, 0x03, 0x1f, 0xbd, 0x95, 0x21, 0x7d, 0x80, 0x85, 0x5a, 0xd3, 0xb3, 0x63,
	0xd8, 0xbb, 0x96, 0x71, 0x70, 0x13, 0xc8, 0x61, 0x4a, 0xf1, 0x14, 0x2a, 0x6e, 0x3c, 0xb8, 0x76,
	0x4d, 0x44, 0xf6, 0xc2, 0xeb, 0x06, 0xaf, 0x81, 0x72, 0xdb, 0x1b, 0x88, 0xbd, 0x84, 0x9d, 0xeb,
	0x48, 0xcb, 0x64, 0x73, 0x45, 0x3e, 0x81, 0xc6, 0x3b, 0x4f, 0xe1, 0x48, 0x64, 0x1f, 0x83, 0x7d,
	0x4f, 0x9e, 0x71, 0x63, 0xef, 0xf3, 0xb0, 0xf7, 0x32, 0x08, 0x87, 0x86, 0xdc, 0xd2, 0x4c, 0x33,
	0xdd, 0x99, 0xfb, 0x50, 0x77, 0x3e, 0x59, 0xb2, 0x18, 0x32, 0x4e, 0xbd, 0xb5, 0xe3, 0xa7, 0xac,
	0xf8, 0x92, 0xe4, 0xfe, 0x9f, 0x50, 0x46, 0x61, 0x93, 0x9f, 0x63, 0x10, 0x02, 0x45, 0x93, 0xb0,
	0xa3, 0x24, 0x5c, 0x9b, 0x7b, 0x94, 0xd4, 0x13, 0x39, 0xa9, 0xc6, 0x53, 0x39, 0x65, 0xbb, 0xb2,
	0xc7, 0x76, 0x1f, 0x41, 0xc9, 0xfc, 0xb6, 0x1c, 0x09, 0x6d, 0x28, 0x83, 0xb5, 0x9b, 0xa9, 0xd0,
	0x51, 0x08, 0x9f, 0xb4, 0xb7, 0xa3, 0x8a, 0xf4, 0x98, 0x55, 0xb2, 0x3f, 0x72, 0xd0, 0xf0, 0xa3,
	0xd7, 0xc6, 0xe7, 0x23, 0xd8, 0xf1, 0x79, 0xa4, 0xed, 0x86, 0x68, 0x56, 0xe9, 0x0f, 0xd9, 0x42,
	0x76, 0xc8, 0x6e, 0xfa, 0xe6, 0x03, 0x28, 0x73, 0x29, 0x54, 0x14, 0xba, 0x2f, 0x76, 0x92, 0xe1,
	0x8e, 0xde, 0x38, 0x96, 0x6a, 0x1c, 0x4d, 0x86, 0xf8, 0xd1, 0x35, 0xbe, 0x54, 0x20, 0x6b, 0x25,
	0xc2, 0xe5, 0x8d, 0x61, 0x21, 0x37, 0x4b, 0x57, 0xd5, 0xec, 0x1a, 0xee, 0x9d, 0x46, 0x91, 0x56,
	0x5a, 0xc4, 0xb3, 0xee, 0x22, 0x1c, 0xa4, 0x1f, 0xe7, 0x03, 0x9a, 0xfb, 0x7b, 0x40, 0x37, 0x4c,
	0x1a, 0x46, 0xa1, 0xd8, 0x5f, 0x68, 0xb9, 0xe1, 0xc9, 0xf2, 0x3d, 0x34, 0xcc, 0xc9, 0xe9, 0x41,
	0x09, 0x33, 0xe6, 0xb6, 0x31, 0x63, 0x7e, 0x95, 0x19, 0x3d, 0xae, 0x2b, 0x64, 0xb8, 0x8e, 0xfd,
	0x99, 0x07, 0xba, 0xad, 0x9b, 0x3d, 0xb8, 0x6a, 0x08, 0x17, 0x81, 0xe2, 0xcb, 0x38, 0x9a, 0x3a,
	0x94, 0x70, 0x6d, 0x7c, 0x7a, 0x91, 0xdb, 0x35, 0xdf, 0x8b, 0x70, 0xb8, 0x4e, 0xa3, 0x79, 0xa8,
	0x11, 0x94, 0x12, 0x77, 0x52, 0x36, 0xc1, 0xd2, 0x06, 0xea, 0xee, 0x6a, 0xa1, 0xe7, 0xca, 0x21,
	0xe3, 0x24, 0x0f, 0xcc, 0x4a, 0xb3, 0xe0, 0x81, 0x79, 0x0c, 0x15, 0x4b, 0xac, 0xca, 0x8d, 0x41,
	0xb2, 0x76, 0x55, 0x15, 0x4f, 0x5c, 0x8c, 0xb7, 0x7d, 0x29, 0xd9, 0x01, 0xb8, 0xc5, 0xdb, 0xb9,
	0x90, 0xc7, 0x50, 0x44, 0xfc, 0x61, 0xab, 0x2b, 0xda, 0x7d, 0x62, 0xaa, 0x67, 0x88, 0xc9, 0x2f,
	0x77, 0x23, 0x5b, 0xee, 0x1f, 0x60, 0xf7, 0x42, 0xfe, 0xe4, 0xf5, 0x88, 0xa9, 0xe9, 0x8d, 0xa9,
	0xa9, 0xad, 0x32, 0xae, 0x4d, 0x4d, 0x75, 0xe4, 0xaa, 0x9c, 0xd7, 0x58, 0x53, 0x61, 0x6b, 0x6a,
	0x5f, 0x92, 0x4e, 0x32, 0x35, 0x55, 0x69, 0x4d, 0x6d, 0x0f, 0x2c, 0x15, 0xec, 0x02, 0x6e, 0x67,
	0xcf, 0x52, 0xe4, 0xb3, 0xd5, 0xe3, 0x1d, 0xdf, 0xdd, 0xc1, 0x8f, 0xcc, 0x9a, 0xf8, 0x8a, 0x2b,
	0x7b, 0x07, 0x0f, 0xb6, 0xdd, 0x14, 0x45, 0xbe, 0x03, 0xaa, 0xb7, 0x18, 0xdd, 0x19, 0x1f, 0x98,
	0x1c, 0x5b, 0xc3, 0xd9, 0xaf, 0x39, 0x28, 0x9f, 0x4d, 0x02, 0x19, 0x6a, 0x53, 0xac, 0x50, 0x4c,
	0x93, 0x41, 0x80, 0x6b, 0x53, 0x6c, 0x91, 0x7d, 0x82, 0x3b, 0xd1, 0x94, 0x67, 0x36, 0xef, 0x4f,
	0x82, 0x81, 0x79, 0x19, 0xdb, 0x1b, 0xba, 0x54, 0x90, 0xff, 0x01, 0xcc, 0xe2, 0xe0, 0x9d, 0xd0,
	0xd2, 0x98, 0x6d, 0xf5, 0x3c, 0x8d, 0x57, 0xf4, 0x92, 0x5f, 0x74, 0xf6, 0x0c, 0x2a, 0x36, 0x1b,
	0xc3, 0xcb, 0xe5, 0x01, 0x2e, 0xdd, 0x27, 0xda, 0xd1, 0x6a, 0xad, 0xdc, 0x99, 0x98, 0x82, 0x3d,
	0x44, 0xdf, 0x9f, 0x89, 0xab, 0x8d, 0xf5, 0x02, 0x8a, 0x43, 0xcb, 0x07, 0xff, 0xa0, 0x52, 0xe8,
	0x9a, 0xed, 0xa7, 0xc2, 0x4a, 0x3f, 0xb1, 0x6b, 0xd8, 0x5f, 0x3d, 0x54, 0x91, 0x93, 0xf5, 0x4c,
	0x5c, 0xe2, 0xf7, 0xf0, 0xc4, 0x55, 0x23, 0x5f, 0x73, 0x67, 0xf7, 0xa1, 0xf0, 0x56, 0x2e, 0x0c,
	0x47, 0xbd, 0x95, 0x0b, 0xf7, 0x01, 0x66, 0xc9, 0x3e, 0x87, 0xba, 0x69, 0x8a, 0xb6, 0x1c, 0x04,
	0x53, 0x31, 0x31, 0x4f, 0x2e, 0xfb, 0x78, 0xca, 0xd9, 0x27, 0x97, 0x7d, 0x36, 0x51, 0xa8, 0x38,
	0x07, 0xf7, 0x07, 0x2b, 0x11, 0xd9, 0xa9, 0xa5, 0x38, 0x27, 0x2a, 0xd2, 0xca, 0x6c, 0xe7, 0xb2,
	0xdc, 0xb3, 0xc3, 0x74, 0xa9, 0xe7, 0xbe, 0x13, 0xfb, 0x0f, 0x3c, 0x38, 0x99, 0xcc, 0xc6, 0xc2,
	0xf6, 0x71, 0x2f, 0xba, 0xd4, 0x63, 0x19, 0xbb, 0xa6, 0x6e, 0xfd, 0x9e, 0x83, 0xa2, 0xf9, 0xa7,
	0x49, 0x9e, 0x43, 0xb5, 0x2b, 0x16, 0xe7, 0x72, 0x32, 0x89, 0x88, 0xdd, 0xd0, 0xfb, 0x03, 0x7a,
	0xb8, 0xa6, 0x61, 0xb7, 0x48, 0x0b, 0x8a, 0x86, 0xe7, 0x89, 0x7d, 0x51, 0xb8, 0x3f, 0x11, 0x87,
	0x87, 0xb6, 0x64, 0x9b, 0x26, 0x01, 0xbb, 0x45, 0x3e, 0x05, 0x30, 0x1a, 0xf7, 0xc7, 0xe2, 0x5f,
	0x44, 0xf6, 0xcb, 0xf8, 0xef, 0xf8, 0xe3, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xed, 0xef, 0x68,
	0x3a, 0x2a, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PingClient is the client API for Ping service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingClient interface {
	SayHello(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error)
	Sync(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BootstarpSyncResponse, error)
	SyncAction(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BootstarpSyncResponse, error)
}

type pingClient struct {
	cc *grpc.ClientConn
}

func NewPingClient(cc *grpc.ClientConn) PingClient {
	return &pingClient{cc}
}

func (c *pingClient) SayHello(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error) {
	out := new(PingMessage)
	err := c.cc.Invoke(ctx, "/api.Ping/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingClient) Sync(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BootstarpSyncResponse, error) {
	out := new(BootstarpSyncResponse)
	err := c.cc.Invoke(ctx, "/api.Ping/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingClient) SyncAction(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BootstarpSyncResponse, error) {
	out := new(BootstarpSyncResponse)
	err := c.cc.Invoke(ctx, "/api.Ping/SyncAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingServer is the server API for Ping service.
type PingServer interface {
	SayHello(context.Context, *PingMessage) (*PingMessage, error)
	Sync(context.Context, *Request) (*BootstarpSyncResponse, error)
	SyncAction(context.Context, *Request) (*BootstarpSyncResponse, error)
}

// UnimplementedPingServer can be embedded to have forward compatible implementations.
type UnimplementedPingServer struct {
}

func (*UnimplementedPingServer) SayHello(ctx context.Context, req *PingMessage) (*PingMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedPingServer) Sync(ctx context.Context, req *Request) (*BootstarpSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (*UnimplementedPingServer) SyncAction(ctx context.Context, req *Request) (*BootstarpSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncAction not implemented")
}

func RegisterPingServer(s *grpc.Server, srv PingServer) {
	s.RegisterService(&_Ping_serviceDesc, srv)
}

func _Ping_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Ping/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).SayHello(ctx, req.(*PingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ping_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Ping/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).Sync(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ping_SyncAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).SyncAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Ping/SyncAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).SyncAction(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Ping",
	HandlerType: (*PingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Ping_SayHello_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _Ping_Sync_Handler,
		},
		{
			MethodName: "SyncAction",
			Handler:    _Ping_SyncAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
